ifeq ($(config),debug)
    CXXFLAGS += -pthread -fPIC -std=c++11 -I../.. -L../lib -L$(shell llvm-config --libdir) -g -O0
else
    CXXFLAGS += -pthread -fPIC -std=c++11 -I../.. -L../lib -L$(shell llvm-config --libdir) -DNDEBUG -O3
endif

