config := release

ifeq ($(config),debug)
    CXXFLAGS += -pthread -fPIC -std=c++11 -I../.. -L../lib/debug -L$(shell llvm-config --libdir) -g -O0
    CFLAGS += -pthread -fPIC -I../.. -g -O0
else
    CXXFLAGS += -pthread -fPIC -std=c++11 -I../.. -L../lib/release -L$(shell llvm-config --libdir) -DNDEBUG -O3
    CFLAGS += -pthread -fPIC -I../.. -DNDEBUG -O3
endif



